# Generated by Django 2.1.14 on 2020-02-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200210_2327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productinvoice',
            unique_together={('product', 'invoice')},
        ),
    ]
